### ISSUE TITLE
Unsuccessful response from userinfo doesn't get forwarded properly

### ISSUE THREAD

**Issue by hygt** [BlueBrain/nexus-iam#37]
IAM replies with an InternalServerError while it should be Unauthorized

**Comment by umbreak** [comment]
When requesting for ACLS (`GET .../acls/some/acls`) with a wrong `Authorization` token, the response is `HTTP 500` with the payload `{"code":"Something bad happened, can't tell you exactly what; want to try again?"}`.

It should return `401 Unathorized` instead, and some other payload with a clearer error signaling.

**Comment by umbreak** [comment]
Still happening. When calling a resource like `.../acls/some./path`, the method [getUser](https://github.com/BlueBrain/nexus-iam/blob/cbd275b246cba73579aad8044cd7737dcef43562/modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/auth/DownstreamAuthClient.scala#L66) gets called and it raises `UnexpectedUnsuccessfulHttpResponse` and this is not defined on the RejectionHandling or anywhere else. 

That's why in the logs you see `2017-10-20 14:23:50 WARN  c.e.b.n.i.s.r.ExceptionHandling$ - An unexpected error has happened 'Received an unexpected http response while communicating with an external service'`

**Comment by bogdanromanx** [comment]
@umbreak is this still an issue?

**Comment by hygt** [comment]
@bogdanromanx yes, the `authenticateOAuth2Async` directive doesn't handle exceptions, I need to deal with that.
